### ISSUE TITLE
Dev?

### ISSUE THREAD

**Issue by MikkelDK** [JimTR/LGSM-Web#4]
Hi, @JimTR is this still active?

**Comment by JimTR** [comment]
Yes but I have spent the last year or so changing the approach on how to do this as it is written in php I have coded for both the command line & web pages however I do need help with the web (html/java) if you know anyone

**Comment by MikkelDK** [comment]
I can do some simple html =) if needs. =D

**Comment by JimTR** [comment]
maybe we can chat some time & perhaps work something out

**Comment by JimTR** [comment]
![Screenshot from 2019-12-09 18:50:03](https://user-images.githubusercontent.com/4038510/70463696-48bd7500-1ab5-11ea-9fcc-0d8af3076248.png)
current cli details page

**Comment by MikkelDK** [comment]
Not bad. - do you think, it will be possible to control like (user) can start/stop own gameserver from interface?
